const suits = ["H", "D", "C", "S"];
const values = [10,10,10,"A", "A", "A", "A", "A", "A"];
let deck = new Deck(6);
let discardDeck = [];
deck.createDeck(suits, values);
deck.shuffle();
deck.shuffle();
var table = document.getElementById("table");
let game = new Table();
//game.showPlayersCards();
